//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketSenderClientWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocketSenderClientWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:simpleType name=&quot;messageType&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///      &lt;xs:pattern value=&quot;([a-fA-F0-9][a-fA-F0-9])+&quot; /&gt;
        ///    &lt;/xs:restriction&gt;
        ///  &lt;/xs:simpleType&gt;
        ///
        ///  &lt;xs:element name=&quot;messages&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;message&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;messages&gt;
        ///	&lt;message name=&quot;NightMode: Off&quot;&gt;100600&lt;/message&gt;
        ///	&lt;message name=&quot;NightMode: On&quot;&gt;100601&lt;/message&gt;
        ///&lt;/messages&gt;.
        /// </summary>
        internal static string messages_default {
            get {
                return ResourceManager.GetString("messages_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;messages&gt;
        ///	&lt;message name=&quot;test1&quot;&gt;1F&lt;/message&gt;
        ///	&lt;message name=&quot;test2&quot;&gt;2E&lt;/message&gt;
        ///	&lt;message name=&quot;test3&quot;&gt;3D&lt;/message&gt;
        ///&lt;/messages&gt;.
        /// </summary>
        internal static string messages_example {
            get {
                return ResourceManager.GetString("messages_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:simpleType name=&quot;messageType&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///      &lt;xs:pattern value=&quot;([a-fA-F0-9][a-fA-F0-9])+&quot; /&gt;
        ///    &lt;/xs:restriction&gt;
        ///  &lt;/xs:simpleType&gt;
        ///
        ///  &lt;xs:element name=&quot;sequence&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:choice maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;message&quot;&gt;
        ///            &lt;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sequence {
            get {
                return ResourceManager.GetString("sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;sequence&gt;
        ///	&lt;message name=&quot;test1&quot;&gt;1F&lt;/message&gt;
        ///	&lt;delay&gt;7000&lt;/delay&gt;
        ///	&lt;message name=&quot;test2&quot;&gt;2E&lt;/message&gt;
        ///	&lt;message name=&quot;test3&quot;&gt;3D&lt;/message&gt;
        ///	&lt;delay&gt;1&lt;/delay&gt;
        ///&lt;/sequence&gt;.
        /// </summary>
        internal static string sequence_example {
            get {
                return ResourceManager.GetString("sequence_example", resourceCulture);
            }
        }
    }
}
